public class ashok {
public integer firstvalue;
    public integer secondvalue;
    
    public integer addition(integer firstvalue,integer secondvalue){
        integer sum=firstvalue+secondvalue;
        return sum;
    }
     
    public void addition1(){
        integer sum=firstvalue+secondvalue;
        //return sum;
        system.debug(sum);
    }
     public void subraction1(){
        integer sub=firstvalue-secondvalue;
        //return sub;
        system.debug(sub);
    }
    public integer subraction(integer firstvalue,integer secondvalue){
        integer sub=firstvalue-secondvalue;
        return sub;
    }
    
    
    
    public void multiplication1(){
        integer mul=firstvalue*secondvalue;
        //return sub;
        system.debug(mul);
    }
    
  public integer multiplication (integer firstvalue,integer secondvalue){
        integer mul=firstvalue*secondvalue;
        return mul;    
  }
}