public class mypracticeclass {
    integer fristvalue  = 10; 
    integer secondvalue = 40;
    
      public  integer addition(){ 
        integer sum= (fristvalue+secondvalue);  
       return sum;
    }
        
     public integer subtrations(){
        integer sub=(fristvalue-secondvalue);
        return sub;
    }
    
   public integer  multipucation(){
        integer mul= (fristvalue * secondvalue);
      return mul ;
  }
   public  integer division(){
        
        integer div=(fristvalue/secondvalue);
        return div;
    } 
}