public class mypracticeclass2 {
    
  integer fristvalue = 20;
  integer secondvalue = 40;
    
     integer addition(){
        
       integer sum= (fristvalue+secondvalue);
         return sum;
    }
    
    
   integer subtrations(){
        
        integer sub =(fristvalue-secondvalue);
        return sub;
    }
    
integer multiplation(){
        
        integer mul =(fristvalue*secondvalue);
     return mul;
    }
    
    public void mypracticeclass2(){
        system.debug(fristvalue+secondvalue);
        system.debug(fristvalue-secondvalue);
        system.debug(fristvalue*secondvalue);
    }
    
    
    
}